version: '2'

services:

  front:
    image: adamkingsbury/rpi-mailu-nginx
    restart: always
    env_file: .env
    ports:
    - "$BIND_ADDRESS4:110:110"
    - "$BIND_ADDRESS4:143:143"
    - "$BIND_ADDRESS4:993:993"
    - "$BIND_ADDRESS4:995:995"
    - "$BIND_ADDRESS4:25:25"
    - "$BIND_ADDRESS4:465:465"
    - "$BIND_ADDRESS4:587:587"
    volumes:
      - "$ROOT/certs:/certs"
    networks:
      - mailu
    labels:
      - "traefik.backend=mailu"
      - "traefik.frontend.rule=Host:mail.soln.ltd"
      - "traefik.enable=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.default.protocol=http"
      - "traefik.default.port=80"
      - "traefik.secure.protocol=https"
      - "traefik.secure.port=443"


  redis:
    image: arm32v6/redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  imap:
    image: adamkingsbury/rpi-mailu-dovecot
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  smtp:
    image: adamkingsbury/rpi-mailu-postfix
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  antispam:
    image: adamkingsbury/rpi-mailu-rspamd
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  antivirus:
    image: adamkingsbury/rpi-mailu-none
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/data"
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  webdav:
    image: adamkingsbury/rpi-mailu-radicale
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/dav:/data"
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  admin:
    image: adamkingsbury/rpi-mailu-admin
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  webmail:
    image: adamkingsbury/rpi-mailu-roundcube
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/webmail:/data"
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

  fetchmail:
    image: adamkingsbury/rpi-mailu-fetchmail
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
    networks:
      - mailu
    labels:
      - "traefik.enable=false"

networks:
  mailu:
    external:
      name: mailu
